### ISSUE TITLE
Get Documentation online.

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/findbugs-maven-plugin-old#1]

**Comment by Klortho** [comment]
+1

In case anybody else wanders by, I finally found it on the wayback machine [here](https://web.archive.org/web/20150521142446/http://gleclaire.github.io/findbugs-maven-plugin).

**Comment by hboutemy** [comment]
documentation published: http://www.mojohaus.org/findbugs-maven-plugin/

**Comment by hboutemy** [comment]
after publishing documentation for the code that is here at mojohaus, I found that it is an old version (2.5.3-SNPASHOT)
seems gleclaire maintained it outside mojohaus organization at http://gleclaire.github.io/findbugs-maven-plugin/

We need to see with Garvin what he wants to do:
1. continue maintenance outside mojohaus: mojohaus will have to point to Garvin version (which is de-facto reference)
2. push back code to mojohaus

Reopening...

**Comment by hboutemy** [comment]
seen with Garvin: forking his private temporary git repo to MojoHaus
now http://www.mojohaus.org/findbugs-maven-plugin/ is back as the main site

this git repo is renamed to findbugs-maven-plugin-old just to keep the issues while we switch to the new github repo
